### PR TITLE
Update ResourceTableRow.vue

### PR DESCRIPTION
**Pull request by mstaack**
pass resource prop, to fix bug with latest nova 3.27 release:
https://github.com/laravel/nova-issues/issues/3463

### CODE REVIEW

**Comment by mstaack** [comment]
@Tarpsvo please consider merging this ;)

all the best & thank you for these nice packages.

**Review by Tarpsvo — APPROVED** [review]

**Comment by Tarpsvo** [comment]
Hey! Sorry for the delay! Even though it's summer, I have a ridiculous amount of things in my TODO list. I'm trying my best to have one day of the week for open source maintenance. :) I will address some other issues and then create a release. Thank you!

**Comment by dvigueras** [comment]
@Tarpsvo thanks for merging. Waiting for the release to be able to update to the lastest Nova release.

**Comment by Tarpsvo** [comment]
The 2.3.4 release is now published!

**Comment by mstaack** [comment]
@Tarpsvo thank you !

**Pull request merged**
