### PR TITLE
Added FR lang translations

### PR DESCRIPTION
**Pull request by Nyratas**
It's all in the title.

### CODE REVIEW

**Comment by Tarpsvo** [comment]
Cheers!

**Comment by Nyratas** [comment]
Hi @Tarpsvo, would it be possible to publish a release with the new translation files? Thanks!

**Comment by Tarpsvo** [comment]
Hi! Published it in version 1.4.8. Good luck!

**Comment by Nyratas** [comment]
Great, thanks a lot!

**Pull request merged**
